<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Quizz</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="questions.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <Target Name="DownloadSignalRJs" BeforeTargets="Build" Condition="!Exists('wwwroot/lib/signalr/signalr.min.js')">
    <Message Text="Downloading SignalR client JS..." Importance="high" />
    <MakeDir Directories="wwwroot/lib/signalr" />
    <DownloadFile SourceUrl="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/8.0.7/signalr.min.js" DestinationFolder="wwwroot/lib/signalr/" />
  </Target>
</Project>
